Schedule component
CruzHacks/cruzhacks-2022-website pull request #158
Opened 2021-12-28 23:53 UTC by w-gao

Problem
=======
Schedule component [Jira](https://cruzhacks-dev.atlassian.net/browse/C2D-74)

Solution
========
What I/we did to solve this problem
* Create Schedule component

Change Summary:
---------------
* Schedule component layout on desktop d18b166
* Responsiveness 3e8559f

Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
- [ ] Key & Sample value to `.env` & `sample.env` 
- [ ] GCP Secret Manager (Both development and production)
- [ ] Github Secrets (Added a development and production variable)
- [ ] Github Workflows `.github/workflows/dev.yml` & `.github/workflows/prod.yml`
- [ ] webpack-config.js

Images/Important Notes (optional):
-----------------------

* This should probably be merged after #152 and #155; I need to fix the background gradient

* Desktop
<img src="https://user-images.githubusercontent.com/20177171/147615349-860254c5-30bf-4a77-8651-0670587c2133.png" width="500px">

* Tablet
<img src="https://user-images.githubusercontent.com/20177171/147615329-342afedf-df9d-48bd-9a16-194271bed14d.png" width="500px">

* Mobile
<img src="https://user-images.githubusercontent.com/20177171/147615306-58dfc3e6-1b39-44b6-be7a-24c941865d73.png" width="500px">

  - NOTE: should ask design about the arrows on mobile

2021-12-29 04:54 UTC, Alperdec requested changes
Looks really good William! The only comments I have is comparing to figma there seems to be a little more padding between the text and the table fields and the background gradient differences. It looks like we'll have to update the gradient for the FAQ component as well.

2021-12-29 06:24 UTC, krishnakpandian commented on src/views/Home/components/Schedule/components/index.scss
> +      margin: 0;
On desktop, I think the margin should be a little bit higher according to the figma

2021-12-29 06:25 UTC, krishnakpandian commented on src/views/Home/components/Schedule/components/index.scss
> +      margin: 0;
Same as time, for desktop, the margin should be a bit higher

2021-12-29 06:26 UTC, krishnakpandian commented on src/views/Home/components/Schedule/components/index.scss
> +    min-height: 300px;
From the figma, it seems like the table should have the same height for each component and the min-height should be a bit higher on desktop

2021-12-29 06:26 UTC, krishnakpandian requested changes
This looks great! I agree with @Alperdec comments. I think the main thing is that on desktop the vertical sizing is a bit off but overall it looks good.

2021-12-31 19:28 UTC, w-gao commented
Thanks for the review @Alperdec and @krishnakpandian! I adjusted the vertical spacing and made each component the same height, so it should look more like the figma design now.

2022-01-03 00:11 UTC, krishnakpandian commented on src/views/Home/components/Schedule/components/index.scss
> +    font-size: 20px;
Font-size should be closer to 30px on desktop + widescreens. We can use our font macro or screen macro for a quick fix.

2022-01-03 00:14 UTC, krishnakpandian requested changes
I think we are almost there, it still seems a bit rectangular in comparison to the figma for desktop views. The mobile views looks amazing!

2022-01-03 00:14 UTC, krishnakpandian commented on src/views/Home/components/Schedule/components/index.scss
> +    font-size: 20px;
Font-size should be closer to 30px on desktop + widescreens. We can use our font macro or screen macro for a quick fix.

2022-01-03 00:14 UTC, krishnakpandian commented on src/views/Home/components/Schedule/components/index.scss
> +    max-height: 60px;
This seems like it should be closer to 80px on desktop + widescreen.

2022-01-03 00:14 UTC, krishnakpandian commented on src/views/Home/components/Schedule/components/index.scss
> +    height: 500px;
These seem closer to 800px for desktop.

2022-01-03 01:30 UTC, krishnakpandian approved these changes
LGTM

2022-01-03 06:47 UTC, merged